### ISSUE TITLE
Closure::__set_state()

### ISSUE THREAD

**Issue by Michal-sk** [zfcampus/zf-apigility#112]
In my ```module.config.php``` i add a entry to the ```service_manager``` for a factory, lambda style:

```
    'service_manager' => array(
        'factories' => array(
            'Thun\\Model\\V2\\Option\\Option' => function(){
                return (new \Thun\Model\V2\Option\Factory())->create();
            },
        ),
```

Than i make a change in the Admin UI, the value for the factory entry is rewritten to:

```
    'service_manager' => array(
        'factories' => array(
            'Thun\\Model\\V2\\Option\\Option' => Closure::__set_state(array(
            )),
        ),
```

Now i am getting the error

```
Fatal error: Call to undefined method Closure::__set_state() 
```

Am i defining my factory in a wrong place?

**Comment by Michal-sk** [comment]
Related? https://github.com/zfcampus/zf-apigility/issues/95

**Comment by jguittard** [comment]
Yes you are. 
Because of the way zf-configuration handle parameters files with key-values in arrays, you shouldn't put any closure in your API module config file. 
Instead, declare as a value the FQCN of a factory class that implements FactoryInterface and put the logic of your factory inside createService. 

Julien.

**Comment by Michal-sk** [comment]
Ok. I followed what was described on: http://framework.zend.com/manual/current/en/modules/zend.service-manager.intro.html#service-factories
