### ISSUE TITLE
Authentication is always required, even for methods that don't require authorization

### ISSUE THREAD

**Issue by shemetov-info** [zfcampus/zf-apigility#119]
I'm following this https://apigility.org/documentation/intro/first-rest-service REST service tutorial.
First I create basic authentication adapter and apply it for the whole API, then I proceed to Service - Authorization and check all methods but GET.
As I understood from the tutorial, GET methods, both for collection and for entity, should be accessed without authentication, while POST etc must be available for authorized user only. This is not how it works however, even GET requests require authentication and respond with 401 Unauthorized if no authentication data is provided.
When I disable authentication completely, GET requests are working fine, but POST etc return 403 not authorized.
This whole behavior actually makes sense, as I apply authentication for the whole API, but this directly conflicts with tutorial, that says that methods, that don't require authorization, are supposed to be available w/o authentication too.
there are a few stackoverflow threads
http://stackoverflow.com/questions/30226165/how-to-activate-authorization-only-for-some-of-http-methods-in-apigility
https://stackoverflow.com/questions/29940736/basic-auth-in-apigility-when-using-postman
that lead me to conclusion the problem is specific only to HttpAdapter based authorization, as those who use oAuth based solution don't have it

**Comment by weierophinney** [comment]
This issue is due to how browser-based authentication works.

We return a `WWW-Authenticate` header if you have missing HTTP credentials for an API that is behind HTTP authentication. In CLI and machine-based tools (e.g. cURL, wget, HTTPie, etc.), this means you can see that you _could_ pass your credentials; however, due to the non-error status, it's not _required_.

Browsers treat this differently: if the header is present and indicates an HTTP authentication scheme (e.g., Basic or Digest), the browser will prompt the user for credentials, regardless of whether or not the HTTP status indicates credentials are required.

As such, browser-based API testing tools such as Postman tend to have issues when provided a `WWW-Authenticate` header and a success status, and still prompt for the credentials, even if they are not required.

As such, there is no conflict in the tutorial; the API does not require the credentials for those methods. However, the *browser* is not behaving well here.

Our only possibility is to _not_ send the `WWW-Authenticate` header on successful requests, but this also goes against the various HTTP standards, meaning we're at an impasse as to what behavior to specify. Since APIs are generally consumed using client libraries and tooling, the current approach is reasonable, so we are not planning a change at this time.

**Comment by shemetov-info** [comment]
Thanks for the explanation, but I have the same problem with cURL too. a simple request w/o authentication header

curl -i -H 'Accept: application/json' http://apigility.local/status 

ends up with

HTTP/1.1 401 Unauthorized
Server: nginx/1.8.0
Date: Tue, 14 Jul 2015 06:48:58 GMT
Content-Type: application/problem+json
Transfer-Encoding: chunked
Connection: keep-alive
WWW-Authenticate: Basic realm="api"

{"type":"http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html","title":"Unauthorized","status":401,"detail":"Unauthorized"}

so I have to provide auth header, i.e.

--user demo:demo

to get a proper response.
