### ISSUE TITLE
Fatal error when injecting Apigility v1.4 into Zend Framework 3

### ISSUE THREAD

**Issue by divix1988** [zfcampus/zf-apigility#182]
I've juts included 4 new packages: zfcampus/zf-apigility, zfcampus/zf-apigility-admin, zfcampus/zf-development-mode and rwoverdijk/assetmanager (not sure why though but fair enough).
After that the website displays this stack trace:

```

<br />
<b>Fatal error</b>:  Uncaught exception 'Zend\ServiceManager\Exception\ServiceNotFoundException' with message 'Unable to resolve service &quot;InputFilterManager&quot; to a factory; are you certain you provided it during configuration?' in D:\RZECZY_ADAMA\_XAMPP\xampp-5.6\htdocs\zend3\vendor\zendframework\zend-servicemanager\src\ServiceManager.php:670
Stack trace:
#0 D:\RZECZY_ADAMA\_XAMPP\xampp-5.6\htdocs\zend3\vendor\zendframework\zend-servicemanager\src\ServiceManager.php(746): Zend\ServiceManager\ServiceManager-&gt;getFactory('InputFilterMana...')
#1 D:\RZECZY_ADAMA\_XAMPP\xampp-5.6\htdocs\zend3\vendor\zendframework\zend-servicemanager\src\ServiceManager.php(195): Zend\ServiceManager\ServiceManager-&gt;doCreate('InputFilterMana...')
#2 D:\RZECZY_ADAMA\_XAMPP\xampp-5.6\htdocs\zend3\vendor\zfcampus\zf-content-validation\src\ContentValidationListenerFactory.php(31): Zend\ServiceManager\ServiceManager-&gt;get('InputFilterMana...')
#3 D:\RZECZY_ADAMA\_XAMPP\xampp-5.6\htdocs\zend3\vendor\zendframework\zend-servicemanager\src\ServiceManager.php(747):  in <b>D:\RZECZY_ADAMA\_XAMPP\xampp-5.6\htdocs\zend3\vendor\zendframework\zend-servicemanager\src\ServiceManager.php</b> on line <b>670</b><br />
```

**EDIT:** It turns up, that I needed another pacakge: Zend\InputFilter, after importing it via Composer and adding it into modules.config.php it started to show my previous website. **I still can't see Administration Panel of Apigility after running: php public/index.php development enable.**

**Comment by webimpress** [comment]
So what error you can see now?
As I understand, previous error was caused because you didn't enable `Zend\InputFilter` module, correct?

**Comment by divix1988** [comment]
@webimpress thanks for your reply.
That is correct, atm I don't know how to access Apigility Administration Panel when I am in development enable mode. I can access things like: apigility/api/module/StatusLib which returns me some json, but that's about it. How do I see Apigility GUI?

**Comment by webimpress** [comment]
@divix1988 Please read the documentation:
https://apigility.org/documentation/intro/updating-to-1-4#asset-management

In Apigility 1.4 asset management was changed. As you noted before you've installed `rwoverdijk/assetmanager` (I guess version 1.7). Do you have enabled this module?
Do you have installed module [`zendframework/zend-component-installer `](https://github.com/zendframework/zend-component-installer)?
You can always try install this module, and than remove whole `vendor` directory and run `composer update` (or `composer install`) again. You can also try library `zfcampus/zf-asset-manager` instead of `rwoverdijk/assetmanager`, as described in the documentation. Both are fine and both should work with Apigility 1.4 :)

Definitely you don't need to run bower ;)

**Comment by divix1988** [comment]
OMG finally!!... I've had to add AssetManager to development.config.php & dist (yeah I know this could easily be copied with development-enable script). and it started to work for anybody else who will struggle as me, here is a development.config.php modules list:

```
'modules' => [
    'ZF\Apigility\Admin',
    'ZF\Apigility\Admin\Ui',
    'ZF\Configuration',
    'AssetManager'
],
```

Thanks for your help @webimpress, big help! Dzięki! :)
