### ISSUE TITLE
Existing Service Layer and Doctrine integration

### ISSUE THREAD

**Issue by wesleywillians** [zfcampus/zf-apigility#8]
Hello folks.

I was wondering to use this module with doctrine and I know we have an option to create a new rest service code based.

Imagining I already have a module with a service layer with all my business logic, including my own fetchAll bringing only the records and columns I desire, is there any possibility to use apigility together with this serviceLayer?

If so, Do I still need to use the apigility Entity file? (just remebering I already have my entities because I use doctrine).

All the Best
Wesley

**Comment by tokenpost** [comment]
Hello. I have the same problem.

@vyshane I need your help, man!
I created an entity called User in Application\Entity\User.
I created a rest-service called user (/user[/:user_id]) and in module.config.php I changed the:

'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
by
'hydrator' => 'DoctrineModule\\Stdlib\\Hydrator\\DoctrineObject'

In zf-hal > metadata_map I changed 'api\\V1\\Rest\\User\\UserEntity' to 'Application\\Entity\\User'

And still doesn't work! Could you send an example, please? I can't understando why this rest does not work fine.

Thanks man!

http://pastebin.com/Ds7Ugsbb -> module.config.php
http://pastebin.com/ePXTeEbw -> Entity User

**Comment by Wilt** [comment]
Maybe you can tell us some details on what exactly your problem is.
"It still doesn't work" is not very helpful for trying to find the problem.
What goes wrong? Any errors/exceptions. Some strange response?
Please be more specific. One thing I can say from looking at your code is that the way you registered your `DoctrineObject` hydrator is probably wrong.

The doctrine object hydrator is dependent on an ObjectManager (i.e. EntityManager). So you will need to register it through a factory add it to your hydrator plugin manager. Like this it will most likely not work. But this I consider as not `Apigility` related, this is a `Doctrine` implementation issue.
